// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DaybookEntry: typeof import('./src/components/DaybookEntry.vue')['default']
    DaybookEntryList: typeof import('./src/components/DaybookEntryList.vue')['default']
    DaybookNavbar: typeof import('./src/components/DaybookNavbar.vue')['default']
    IFaSolidPlusCircle: typeof import('~icons/fa-solid/plus-circle')['default']
    IFaSolidSignOutAlt: typeof import('~icons/fa-solid/sign-out-alt')['default']
  }
}

export { }
