// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    EntryList: typeof import('./src/components/EntryList.vue')['default']
    IFaSolidCirclePlus: typeof import('~icons/fa-solid/circle-plus')['default']
    IFaSolidPlusCircle: typeof import('~icons/fa-solid/plus-circle')['default']
    IFaSolidSignOutAlt: typeof import('~icons/fa-solid/sign-out-alt')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
  }
}

export { }
